### ISSUE TITLE
έχει πάρα πολλά αχρηστα dependencies - πρέπει να διορθωθεί - αφού πρόκειται μονο για τον server

### ISSUE THREAD

**Issue by tmanolat** [raven99p/Spa-Employee#1]
https://github.com/raven99p/Spa-Employee/blob/44f89cdc7c7ca6c7a611c095dc898fdcb253adb6/server/package-lock.json#L2

**Comment by raven99p** [comment]
Πράγματι είχε πάρα πολλά, καταλάθος κατέβασα το ant D στο back end directory και ξέχασα να το σβήσω.
